### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/infografia-lucero012#3]
[infografia. act 1.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lucero012/files/7207468/infografia.act.1.pdf)

**Comment by lourdeshernandez2003** [comment]
calificando mediante la rubrica le asigno el 15% porque no cumple con las referencias, no establece,  no lo tiene bien estructurado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
